<!doctype html>
<html ng-app="Categorias">
    <head>
        <title>ZF2 Angular</title>
        <link href="css/bootstrap.min.css" media="screen" type="text/css" rel="stylesheet">
    </head>
    <body>
    <div id="wrap">
        <div class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar">
                        <span class="sr-only">Togle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Zf2Angular</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="#">Categorias</a></li>
                        <li><a href="#">Produtos</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="page-header" ng-controller="CategoriasCtrl">
                <br>
                <?=$this->content;?>
                <div ng-view></div>
            </div>

            <div id="footer">
                <div class="container">
                    <p class="text-muted credit">David Turati</p>
                </div>
            </div>

        </div>
    </div>
    <script src="/js/jquery.min.js"></script>
    <script>var $jQuery = jQuery.noConflict(); </script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.29/angular.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.29/angular-route.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.29/angular-resource.min.js"></script>
    <script src="angular/Categorias.js"></script>
    <script src="angular/CategoriasCtrl.js"></script>
    <script src="angular/CategoriasSrv.js"></script>

    </body>
</html>
